name: Mirror to GitLab & Codeberg

on:
  push:
    branches: ["*"]
    tags: ["*"]
  delete:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ========== ЗЕРКАЛО В GITLAB ==========
      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_REPO: ${{ secrets.GITLAB_REPO }}
        run: |
          git remote remove gitlab 2>/dev/null || true
          git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@${GITLAB_REPO#https://}"
          git push --mirror gitlab

      # ========== ЗЕРКАЛО В CODEBERG ==========
      - name: Push to Codeberg
        env:
          CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
          CODEBERG_REPO: ${{ secrets.CODEBERG_REPO }}
        run: |
          git remote remove codeberg 2>/dev/null || true
          git remote add codeberg "https://${CODEBERG_TOKEN}@${CODEBERG_REPO#https://}"
          git push --mirror codeberg
